export const cidadesSaoPaulo = [
    "Adamantina", "Adolfo", "Aguaí", "Águas da Prata", "Águas de Lindóia", "Águas de Santa Bárbara", 
    "Águas de São Pedro", "Agudos", "Alambari", "Alfredo Marcondes", "Altair", "Altinópolis", 
    "Alto Alegre", "Alumínio", "Álvares Florence", "Álvares Machado", "Álvaro de Carvalho", 
    "Alvinlândia", "Americana", "Américo Brasiliense", "Américo de Campos", "Amparo", "Analândia", 
    "Andradina", "Angatuba", "Anhembi", "Anhumas", "Aparecida", "Aparecida d'Oeste", 
    "Apiaí", "Araçariguama", "Araçatuba", "Araçoiaba da Serra", "Aramina", "Arandu", 
    "Arapeí", "Araraquara", "Araras", "Arco-Íris", "Arealva", "Areias", "Areiópolis", 
    "Ariranha", "Artur Nogueira", "Arujá", "Aspásia", "Assis", "Atibaia", "Auriflama", 
    "Avaí", "Avanhandava", "Avaré", "Bady Bassitt", "Balbinos", "Bálsamo", "Bananal", 
    "Barão de Antonina", "Barbosa", "Bariri", "Barra Bonita", "Barra do Chapéu", 
    "Barra do Turvo", "Barretos", "Barrinha", "Barueri", "Bastos", "Batatais", 
    "Bauru", "Bebedouro", "Bento de Abreu", "Bernardino de Campos", "Bertioga", "Bilac", 
    "Birigui", "Biritiba-Mirim", "Boa Esperança do Sul", "Bocaina", "Bofete", 
    "Boituva", "Bom Jesus dos Perdões", "Bom Sucesso de Itararé", "Borá", "Boracéia", 
    "Borborema", "Borebi", "Botucatu", "Bragança Paulista", "Braúna", "Brejo Alegre", 
    "Brodowski", "Brotas", "Buri", "Buritama", "Buritizal", "Cabrália Paulista", 
    "Cabreúva", "Caçapava", "Cachoeira Paulista", "Caconde", "Cafelândia", 
    "Caiabu", "Caieiras", "Caiuá", "Cajamar", "Cajati", "Cajobi", "Cajuru", 
    "Campina do Monte Alegre", "Campinas", "Campo Limpo Paulista", "Campos do Jordão", 
    "Campos Novos Paulista", "Cananéia", "Canas", "Cândido Mota", "Cândido Rodrigues", 
    "Canitar", "Capão Bonito", "Capela do Alto", "Capivari", "Caraguatatuba", 
    "Carapicuíba", "Cardoso", "Casa Branca", "Cássia dos Coqueiros", "Castilho", 
    "Catanduva", "Catiguá", "Cedral", "Cerqueira César", "Cerquilho", "Cesário Lange", 
    "Charqueada", "Chavantes", "Clementina", "Colina", "Colômbia", "Conchal", 
    "Conchas", "Cordeirópolis", "Coroados", "Coronel Macedo", "Corumbataí", 
    "Cosmópolis", "Cosmorama", "Cotia", "Cravinhos", "Cristais Paulista", 
    "Cruzália", "Cruzeiro", "Cubatão", "Cunha", "Descalvado", "Diadema", 
    "Dirce Reis", "Divinolândia", "Dobrada", "Dois Córregos", "Dolcinópolis", 
    "Dourado", "Dracena", "Duartina", "Dumont", "Echaporã", "Eldorado", 
    "Elias Fausto", "Elisiário", "Embaúba", "Embu das Artes", "Embu-Guaçu", 
    "Emilianópolis", "Engenheiro Coelho", "Espírito Santo do Pinhal", "Espírito Santo do Turvo", 
    "Estiva Gerbi", "Estrela d'Oeste", "Estrela do Norte", "Euclides da Cunha Paulista", 
    "Fartura", "Fernandópolis", "Fernando Prestes", "Fernão", "Ferraz de Vasconcelos", 
    "Flora Rica", "Floreal", "Flórida Paulista", "Florínia", "Franca", 
    "Francisco Morato", "Franco da Rocha", "Gabriel Monteiro", "Gália", 
    "Garça", "Gastão Vidigal", "Gavião Peixoto", "General Salgado", "Getulina", 
    "Glicério", "Guaiçara", "Guaimbê", "Guaíra", "Guapiaçu", "Guapiara", 
    "Guará", "Guaraçaí", "Guaraci", "Guarani d'Oeste", "Guarantã", "Guararapes", 
    "Guararema", "Guaratinguetá", "Guareí", "Guariba", "Guarujá", "Guarulhos", 
    "Guatapará", "Guzolândia", "Herculândia", "Holambra", "Hortolândia", 
    "Iacanga", "Iacri", "Iaras", "Ibaté", "Ibirá", "Ibirarema", "Ibitinga", 
    "Ibiúna", "Icém", "Iepê", "Igaraçu do Tietê", "Igarapava", "Igaratá", 
    "Iguape", "Ilha Comprida", "Ilha Solteira", "Ilhabela", "Indaiatuba", 
    "Indiana", "Indiaporã", "Inúbia Paulista", "Ipaussu", "Iperó", "Ipeúna", 
    "Ipiguá", "Iporanga", "Ipuã", "Iracemápolis", "Irapuã", "Irapuru", 
    "Itaberá", "Itaí", "Itajobi", "Itaju", "Itanhaém", "Itaóca", "Itapecerica da Serra", 
    "Itapetininga", "Itapeva", "Itapevi", "Itapira", "Itapirapuã Paulista", 
    "Itápolis", "Itaporanga", "Itapuí", "Itapura", "Itaquaquecetuba", 
    "Itararé", "Itariri", "Itatiba", "Itatinga", "Itirapina", "Itirapuã", 
    "Itobi", "Itu", "Itupeva", "Ituverava", "Jaborandi", "Jaboticabal", 
    "Jacareí", "Jaci", "Jacupiranga", "Jaguariúna", "Jales", "Jambeiro", 
    "Jandira", "Jardinópolis", "Jarinu", "Jaú", "Jeriquara", "Joanópolis", 
    "João Ramalho", "José Bonifácio", "Júlio Mesquita", "Jumirim", 
    "Jundiaí", "Junqueirópolis", "Juquiá", "Juquitiba", "Lagoinha", 
    "Laranjal Paulista", "Lavínia", "Lavrinhas", "Leme", "Lençóis Paulista", 
    "Limeira", "Lindóia", "Lins", "Lorena", "Lourdes", "Louveira", 
    "Lucélia", "Lucianópolis", "Luís Antônio", "Luiziânia", "Lupércio", 
    "Lutécia", "Macatuba", "Macaubal", "Macedônia", "Magda", "Mairinque", 
    "Mairiporã", "Manduri", "Marabá Paulista", "Maracaí", "Marapoama", 
    "Mariápolis", "Marília", "Marinópolis", "Martinópolis", "Matão", 
    "Mauá", "Mendonça", "Meridiano", "Mesópolis", "Miguelópolis", 
    "Mineiros do Tietê", "Mira Estrela", "Miracatu", "Mirandópolis", 
    "Mirante do Paranapanema", "Mirassol", "Mirassolândia", "Mococa", 
    "Mogi das Cruzes", "Mogi Guaçu", "Mogi Mirim", "Mombuca", "Monções", 
    "Mongaguá", "Monte Alegre do Sul", "Monte Alto", "Monte Aprazível", 
    "Monte Azul Paulista", "Monte Castelo", "Monte Mor", "Monteiro Lobato", 
    "Morro Agudo", "Morungaba", "Motuca", "Murutinga do Sul", "Nantes", 
    "Narandiba", "Natividade da Serra", "Nazaré Paulista", "Neves Paulista", 
    "Nhandeara", "Nipoã", "Nova Aliança", "Nova Campina", "Nova Canaã Paulista", 
    "Nova Castilho", "Nova Europa", "Nova Granada", "Nova Guataporanga", 
    "Nova Independência", "Nova Luzitânia", "Nova Odessa", "Novais", 
    "Novo Horizonte", "Nuporanga", "Ocauçu", "Óleo", "Olímpia", "Onda Verde", 
    "Oriente", "Orindiúva", "Orlândia", "Osasco", "Oscar Bressane", 
    "Osvaldo Cruz", "Ourinhos", "Ouro Verde", "Ouroeste", "Pacaembu", 
    "Palestina", "Palmares Paulista", "Palmeira d'Oeste", "Palmital", 
    "Panorama", "Paraguaçu Paulista", "Paraibuna", "Paraíso", "Paranapanema", 
    "Paranapuã", "Parapuã", "Pardinho", "Pariquera-Açu", "Parisi", 
    "Patrocínio Paulista", "Paulicéia", "Paulínia", "Paulistânia", 
    "Paulo de Faria", "Pederneiras", "Pedra Bela", "Pedranópolis", 
    "Pedregulho", "Pedreira", "Pedrinhas Paulista", "Pedro de Toledo", 
    "Penápolis", "Pereira Barreto", "Pereiras", "Peruíbe", "Piacatu", 
    "Piedade", "Pilar do Sul", "Pindamonhangaba", "Pindorama", "Pinhalzinho", 
    "Piquerobi", "Piquete", "Piracaia", "Piracicaba", "Piraju", "Pirajuí", 
    "Pirangi", "Pirapora do Bom Jesus", "Pirapozinho", "Pirassununga", 
    "Piratininga", "Pitangueiras", "Planalto", "Platina", "Poá", 
    "Poloni", "Pompéia", "Pongaí", "Pontal", "Pontalinda", "Pontes Gestal", 
    "Populina", "Porangaba", "Porto Feliz", "Porto Ferreira", "Potim", 
    "Potirendaba", "Pracinha", "Pradópolis", "Praia Grande", "Pratânia", 
    "Presidente Alves", "Presidente Bernardes", "Presidente Epitácio", 
    "Presidente Prudente", "Presidente Venceslau", "Promissão", "Quadra", 
    "Quatá", "Queiroz", "Queluz", "Quintana", "Rafard", "Rancharia", 
    "Redenção da Serra", "Regente Feijó", "Reginópolis", "Registro", 
    "Restinga", "Ribeira", "Ribeirão Bonito", "Ribeirão Branco", 
    "Ribeirão Corrente", "Ribeirão do Sul", "Ribeirão dos Índios", 
    "Ribeirão Grande", "Ribeirão Pires", "Ribeirão Preto", "Rifaina", 
    "Rincão", "Rinópolis", "Rio Claro", "Rio das Pedras", "Rio Grande da Serra", 
    "Riolândia", "Riversul", "Rosana", "Roseira", "Rubiácea", "Rubinéia", 
    "Sabino", "Sagres", "Sales", "Sales Oliveira", "Salesópolis", 
    "Salmourão", "Saltinho", "Salto", "Salto de Pirapora", "Salto Grande", 
    "Sandovalina", "Santa Adélia", "Santa Albertina", "Santa Bárbara d'Oeste", 
    "Santa Branca", "Santa Clara d'Oeste", "Santa Cruz da Conceição", 
    "Santa Cruz da Esperança", "Santa Cruz das Palmeiras", "Santa Cruz do Rio Pardo", 
    "Santa Ernestina", "Santa Fé do Sul", "Santa Gertrudes", "Santa Isabel", 
    "Santa Lúcia", "Santa Maria da Serra", "Santa Mercedes", "Santa Rita d'Oeste", 
    "Santa Rita do Passa Quatro", "Santa Rosa de Viterbo", "Santa Salete", 
    "Santana da Ponte Pensa", "Santana de Parnaíba", "Santo Anastácio", 
    "Santo André", "Santo Antônio da Alegria", "Santo Antônio de Posse", 
    "Santo Antônio do Aracanguá", "Santo Antônio do Jardim", "Santo Antônio do Pinhal", 
    "Santo Expedito", "Santópolis do Aguapeí", "Santos", "São Bento do Sapucaí", 
    "São Bernardo do Campo", "São Caetano do Sul", "São Carlos", "São Francisco", 
    "São João da Boa Vista", "São João das Duas Pontes", "São João de Iracema", 
    "São João do Pau d'Alho", "São Joaquim da Barra", "São José da Bela Vista", 
    "São José do Barreiro", "São José do Rio Pardo", "São José do Rio Preto", 
    "São José dos Campos", "São Lourenço da Serra", "São Luiz do Paraitinga", 
    "São Manuel", "São Miguel Arcanjo", "São Paulo", "São Pedro", 
    "São Pedro do Turvo", "São Roque", "São Sebastião", "São Sebastião da Grama", 
    "São Simão", "São Vicente", "Sarapuí", "Sarutaiá", "Sebastianópolis do Sul", 
    "Serra Azul", "Serra Negra", "Serrana", "Sertãozinho", "Sete Barras", 
    "Severínia", "Silveiras", "Socorro", "Sorocaba", "Sud Mennucci", 
    "Sumaré", "Suzanápolis", "Suzano", "Tabapuã", "Tabatinga", "Taboão da Serra", 
    "Taciba", "Taguaí", "Taiaçu", "Taiúva", "Tambaú", "Tanabi", 
    "Tapiraí", "Tapiratiba", "Taquaral", "Taquaritinga", "Taquarituba", 
    "Taquarivaí", "Tarabai", "Tarumã", "Tatuí", "Taubaté", "Tejupá", 
    "Teodoro Sampaio", "Terra Roxa", "Tietê", "Timburi", "Torre de Pedra", 
    "Torrinha", "Trabiju", "Tremembé", "Três Fronteiras", "Tuiuti", 
    "Tupã", "Tupi Paulista", "Turiúba", "Turmalina", "Ubarana", 
    "Ubatuba", "Ubirajara", "Uchoa", "União Paulista", "Urânia", 
    "Uru", "Urupês", "Valentim Gentil", "Valinhos", "Valparaíso", 
    "Vargem", "Vargem Grande do Sul", "Vargem Grande Paulista", 
    "Várzea Paulista", "Vera Cruz", "Vinhedo", "Viradouro", 
    "Vista Alegre do Alto", "Vitória Brasil", "Votorantim", "Votuporanga", 
    "Zacarias"
];

export const municipiosRioDeJaneiro = [
    "Angra dos Reis", "Aperibé", "Araruama", "Areal", "Armação dos Búzios", "Arraial do Cabo", 
    "Barra do Piraí", "Barra Mansa", "Belford Roxo", "Bom Jardim", "Bom Jesus do Itabapoana", 
    "Cabo Frio", "Cachoeiras de Macacu", "Cambuci", "Campos dos Goytacazes", "Cantagalo", 
    "Carapebus", "Cardoso Moreira", "Carmo", "Casimiro de Abreu", "Comendador Levy Gasparian", 
    "Conceição de Macabu", "Cordeiro", "Duas Barras", "Duque de Caxias", "Engenheiro Paulo de Frontin", 
    "Guapimirim", "Iguaba Grande", "Itaboraí", "Itaguaí", "Italva", "Itaocara", "Itaperuna", 
    "Itatiaia", "Japeri", "Laje do Muriaé", "Macaé", "Macuco", "Magé", "Mangaratiba", 
    "Maricá", "Mendes", "Mesquita", "Miguel Pereira", "Miracema", "Natividade", 
    "Nilópolis", "Niterói", "Nova Friburgo", "Nova Iguaçu", "Paracambi", "Paraíba do Sul", 
    "Paraty", "Paty do Alferes", "Petrópolis", "Pinheiral", "Piraí", "Porciúncula", 
    "Porto Real", "Quatis", "Queimados", "Quissamã", "Resende", "Rio Bonito", 
    "Rio Claro", "Rio das Flores", "Rio das Ostras", "Rio de Janeiro", "Santa Maria Madalena", 
    "Santo Antônio de Pádua", "São Fidélis", "São Francisco de Itabapoana", "São Gonçalo", 
    "São João da Barra", "São João de Meriti", "São José de Ubá", "São José do Vale do Rio Preto", 
    "São Pedro da Aldeia", "São Sebastião do Alto", "Sapucaia", "Saquarema", "Seropédica", 
    "Silva Jardim", "Sumidouro", "Tanguá", "Teresópolis", "Trajano de Moraes", 
    "Três Rios", "Valença", "Varre-Sai", "Vassouras", "Volta Redonda"
];

export const municipiosRS = [
    "Aceguá", "Água Santa", "Agudo", "Ajuricaba", "Alecrim", "Alegrete", "Alegria",
    "Almirante Tamandaré do Sul", "Alpestre", "Alto Alegre", "Alto Feliz", "Alvorada",
    "Amaral Ferrador", "Ametista do Sul", "André da Rocha", "Anta Gorda", "Antônio Prado",
    "Arambaré", "Araricá", "Aratiba", "Arroio do Meio", "Arroio do Sal", "Arroio do Padre",
    "Arroio dos Ratos", "Arroio Grande", "Arvorezinha", "Augusto Pestana", "Áurea",
    "Bagé", "Balneário Pinhal", "Barão", "Barão de Cotegipe", "Barão do Triunfo",
    "Barra do Guarita", "Barra do Quaraí", "Barra do Ribeiro", "Barra do Rio Azul",
    "Barra Funda", "Barracão", "Barros Cassal", "Benjamin Constant do Sul", "Bento Gonçalves",
    "Boa Vista das Missões", "Boa Vista do Buricá", "Boa Vista do Cadeado", "Boa Vista do Incra",
    "Boa Vista do Sul", "Bom Jesus", "Bom Princípio", "Bom Progresso", "Bom Retiro do Sul",
    "Boqueirão do Leão", "Bossoroca", "Bozano", "Braga", "Brochier", "Butiá", "Caçapava do Sul",
    "Cacequi", "Cachoeira do Sul", "Cachoeirinha", "Cacique Doble", "Caibaté", "Caiçara",
    "Camaquã", "Camargo", "Cambará do Sul", "Campestre da Serra", "Campina das Missões",
    "Campinas do Sul", "Campo Bom", "Campo Novo", "Campos Borges", "Candelária", "Cândido Godói",
    "Candiota", "Canela", "Canguçu", "Canoas", "Canudos do Vale", "Capão Bonito do Sul",
    "Capão da Canoa", "Capão do Cipó", "Capão do Leão", "Capela de Santana", "Capitão",
    "Capivari do Sul", "Caraá", "Carazinho", "Carlos Barbosa", "Carlos Gomes", "Casca",
    "Caseiros", "Catuípe", "Caxias do Sul", "Centenário", "Cerrito", "Cerro Branco", "Cerro Grande",
    "Cerro Grande do Sul", "Cerro Largo", "Chapada", "Charqueadas", "Charrua", "Chiapetta",
    "Chuí", "Chuvisca", "Cidreira", "Ciríaco", "Colinas", "Colorado", "Condor", "Constantina",
    "Coqueiro Baixo", "Coqueiros do Sul", "Coronel Barros", "Coronel Bicaco", "Coronel Pilar",
    "Cotiporã", "Coxilha", "Crissiumal", "Cristal", "Cristal do Sul", "Cruz Alta", "Cruzaltense",
    "Cruzeiro do Sul", "David Canabarro", "Derrubadas", "Dezesseis de Novembro", "Dilermando de Aguiar",
    "Dois Irmãos", "Dois Irmãos das Missões", "Dois Lajeados", "Dom Feliciano", "Dom Pedrito",
    "Dom Pedro de Alcântara", "Dona Francisca", "Doutor Maurício Cardoso", "Doutor Ricardo",
    "Eldorado do Sul", "Encantado", "Encruzilhada do Sul", "Engenho Velho", "Entre Rios do Sul",
    "Entre-Ijuís", "Erebango", "Erechim", "Ernestina", "Erval Grande", "Erval Seco", "Esmeralda",
    "Esperança do Sul", "Espumoso", "Estação", "Estância Velha", "Esteio", "Estrela",
    "Estrela Velha", "Eugênio de Castro", "Fagundes Varela", "Farroupilha", "Faxinal do Soturno",
    "Faxinalzinho", "Fazenda Vilanova", "Feliz", "Flores da Cunha", "Floriano Peixoto", "Fontoura Xavier",
    "Formigueiro", "Forquetinha", "Fortaleza dos Valos", "Frederico Westphalen", "Garibaldi",
    "Garruchos", "Gaurama", "General Câmara", "Gentil", "Getúlio Vargas", "Giruá", "Glorinha",
    "Gramado", "Gramado dos Loureiros", "Gramado Xavier", "Gravataí", "Guabiju", "Guaíba",
    "Guaporé", "Guarani das Missões", "Harmonia", "Herval", "Herveiras", "Horizontina", "Hulha Negra",
    "Humaitá", "Ibarama", "Ibiaçá", "Ibiraiaras", "Ibirapuitã", "Ibirubá", "Igrejinha", "Ijuí",
    "Ilópolis", "Imbé", "Imigrante", "Independência", "Inhacorá", "Ipê", "Ipiranga do Sul",
    "Iraí", "Itaara", "Itacurubi", "Itapuca", "Itaqui", "Itati", "Itatiba do Sul", "Ivorá",
    "Ivoti", "Jaboticaba", "Jacuizinho", "Jacutinga", "Jaguarão", "Jaguari", "Jaquirana",
    "Jari", "Jóia", "Júlio de Castilhos", "Lagoa Bonita do Sul", "Lagoa dos Três Cantos",
    "Lagoa Vermelha", "Lagoão", "Lajeado", "Lajeado do Bugre", "Lavras do Sul", "Liberato Salzano",
    "Lindolfo Collor", "Linha Nova", "Maçambará", "Machadinho", "Mampituba", "Manoel Viana",
    "Maquiné", "Maratá", "Marau", "Marcelino Ramos", "Mariana Pimentel", "Mariano Moro",
    "Marques de Souza", "Mata", "Mato Castelhano", "Mato Leitão", "Mato Queimado", "Maximiliano de Almeida",
    "Minas do Leão", "Miraguaí", "Montauri", "Monte Alegre dos Campos", "Monte Belo do Sul",
    "Montenegro", "Mormaço", "Morrinhos do Sul", "Morro Redondo", "Morro Reuter", "Mostardas",
    "Muçum", "Muitos Capões", "Muliterno", "Não-Me-Toque", "Nicolau Vergueiro", "Nonoai",
    "Nova Alvorada", "Nova Araçá", "Nova Bassano", "Nova Boa Vista", "Nova Bréscia", "Nova Candelária",
    "Nova Esperança do Sul", "Nova Hartz", "Nova Pádua", "Nova Palma", "Nova Petrópolis",
    "Nova Prata", "Nova Ramada", "Nova Roma do Sul", "Nova Santa Rita", "Novo Barreiro",
    "Novo Cabrais", "Novo Hamburgo", "Novo Machado", "Novo Tiradentes", "Novo Xingu",
    "Osório", "Paim Filho", "Palmares do Sul", "Palmeira das Missões", "Palmitinho", "Panambi",
    "Pantano Grande", "Paraí", "Paraíso do Sul", "Pareci Novo", "Parobé", "Passa Sete",
    "Passo do Sobrado", "Passo Fundo", "Paulo Bento", "Paverama", "Pedras Altas", "Pedro Osório",
    "Pejuçara", "Pelotas", "Picada Café", "Pinhal", "Pinhal da Serra", "Pinhal Grande",
    "Pinheirinho do Vale", "Pinheiro Machado", "Pirapó", "Piratini", "Planalto", "Poço das Antas",
    "Pontão", "Ponte Preta", "Portão", "Porto Alegre", "Porto Lucena", "Porto Mauá",
    "Porto Vera Cruz", "Porto Xavier", "Pouso Novo", "Presidente Lucena", "Progresso",
    "Protásio Alves", "Putinga", "Quaraí", "Quatro Irmãos", "Quevedos", "Quinze de Novembro",
    "Redentora", "Relvado", "Restinga Seca", "Rio dos Índios", "Rio Grande", "Rio Pardo",
    "Riozinho", "Roca Sales", "Rodeio Bonito", "Rolador", "Rolante", "Ronda Alta", "Rondinha",
    "Roque Gonzales", "Rosário do Sul", "Sagrada Família", "Saldanha Marinho", "Salto do Jacuí",
    "Salvador das Missões", "Salvador do Sul", "Sananduva", "Santa Bárbara do Sul", "Santa Cecília do Sul",
    "Santa Clara do Sul", "Santa Cruz do Sul", "Santa Margarida do Sul", "Santa Maria",
    "Santa Maria do Herval", "Santa Rosa", "Santa Tereza", "Santa Vitória do Palmar",
    "Santana da Boa Vista", "Santana do Livramento", "Santiago", "Santo Ângelo", "Santo Antônio da Patrulha",
    "Santo Antônio das Missões", "Santo Antônio do Palma", "Santo Antônio do Planalto",
    "Santo Augusto", "Santo Cristo", "Santo Expedito do Sul", "São Borja", "São Domingos do Sul",
    "São Francisco de Assis", "São Francisco de Paula", "São Gabriel", "São Jerônimo",
    "São João da Urtiga", "São João do Polêsine", "São Jorge", "São José das Missões",
    "São José do Herval", "São José do Hortêncio", "São José do Inhacorá", "São José do Norte",
    "São José do Ouro", "São José do Sul", "São José dos Ausentes", "São Leopoldo", "São Lourenço do Sul",
    "São Luiz Gonzaga", "São Marcos", "São Martinho", "São Martinho da Serra", "São Miguel das Missões",
    "São Nicolau", "São Paulo das Missões", "São Pedro da Serra", "São Pedro das Missões",
    "São Pedro do Butiá", "São Pedro do Sul", "São Sebastião do Caí", "São Sepé", "São Valentim",
    "São Valentim do Sul", "São Valério do Sul", "São Vendelino", "São Vicente do Sul",
    "Sapiranga", "Sapucaia do Sul", "Sarandi", "Seberi", "Sede Nova", "Segredo", "Selbach",
    "Senador Salgado Filho", "Sentinela do Sul", "Serafina Corrêa", "Sério", "Sertão",
    "Sertão Santana", "Sete de Setembro", "Severiano de Almeida", "Silveira Martins",
    "Sinimbu", "Sobradinho", "Soledade", "Tabaí", "Tapejara", "Tapera", "Tapes", "Taquara",
    "Taquari", "Taquaruçu do Sul", "Tavares", "Tenente Portela", "Terra de Areia", "Teutônia",
    "Tio Hugo", "Tiradentes do Sul", "Toropi", "Torres", "Tramandaí", "Travesseiro", "Três Arroios",
    "Três Cachoeiras", "Três Coroas", "Três de Maio", "Três Forquilhas", "Três Palmeiras",
    "Três Passos", "Trindade do Sul", "Triunfo", "Tucunduva", "Tunas", "Tupanci do Sul",
    "Tupanciretã", "Tupandi", "Tuparendi", "Turuçu", "Ubiretama", "União da Serra", "Unistalda",
    "Uruguaiana", "Vacaria", "Vale do Sol", "Vale Real", "Vale Verde", "Vanini", "Venâncio Aires",
    "Vera Cruz", "Veranópolis", "Vespasiano Correa", "Viadutos", "Viamão", "Vicente Dutra",
    "Victor Graeff", "Vila Flores", "Vila Lângaro", "Vila Maria", "Vila Nova do Sul",
    "Vista Alegre", "Vista Alegre do Prata", "Vista Gaúcha", "Vitória das Missões", "Westfália",
    "Xangri-lá"
];

export const municipiosRN = [
    "Acari", "Açu", "Afonso Bezerra", "Água Nova", "Alexandria", "Almino Afonso",
    "Alto do Rodrigues", "Angicos", "Antônio Martins", "Apodi", "Areia Branca", 
    "Arês", "Augusto Severo", "Baía Formosa", "Baraúna", "Barcelona", "Bento Fernandes", 
    "Bodó", "Bom Jesus", "Brejinho", "Caiçara do Norte", "Caiçara do Rio do Vento",
    "Caicó", "Campo Redondo", "Canguaretama", "Caraúbas", "Carnaúba dos Dantas",
    "Carnaubais", "Ceará-Mirim", "Cerro Corá", "Coronel Ezequiel", "Coronel João Pessoa",
    "Cruzeta", "Currais Novos", "Doutor Severiano", "Encanto", "Equador", "Espírito Santo",
    "Extremoz", "Felipe Guerra", "Fernando Pedroza", "Florânia", "Francisco Dantas",
    "Frutuoso Gomes", "Galinhos", "Goianinha", "Governador Dix-Sept Rosado", "Grossos",
    "Guamaré", "Ielmo Marinho", "Ipanguaçu", "Ipueira", "Itajá", "Itaú", "Jaçanã",
    "Jandaíra", "Janduís", "Januário Cicco", "Japi", "Jardim de Angicos", 
    "Jardim de Piranhas", "Jardim do Seridó", "João Câmara", "João Dias", "José da Penha",
    "Jucurutu", "Jundiá", "Lagoa d'Anta", "Lagoa de Pedras", "Lagoa de Velhos",
    "Lagoa Nova", "Lagoa Salgada", "Lajes", "Lajes Pintadas", "Lucrécia", "Luís Gomes",
    "Macaíba", "Macau", "Major Sales", "Marcelino Vieira", "Martins", "Maxaranguape",
    "Messias Targino", "Montanhas", "Monte Alegre", "Monte das Gameleiras", "Mossoró",
    "Natal", "Nísia Floresta", "Nova Cruz", "Olho-d'Água do Borges", "Ouro Branco",
    "Paraná", "Paraú", "Parazinho", "Parelhas", "Parnamirim", "Passa e Fica", 
    "Passagem", "Patu", "Pau dos Ferros", "Pedra Grande", "Pedra Preta", "Pedro Avelino",
    "Pedro Velho", "Pendências", "Pilões", "Poço Branco", "Portalegre", "Porto do Mangue",
    "Presidente Juscelino", "Pureza", "Rafael Fernandes", "Rafael Godeiro", "Riacho da Cruz",
    "Riacho de Santana", "Riachuelo", "Rio do Fogo", "Rodolfo Fernandes", "Ruy Barbosa",
    "Santa Cruz", "Santa Maria", "Santana do Matos", "Santana do Seridó", "Santo Antônio",
    "São Bento do Norte", "São Bento do Trairi", "São Fernando", "São Francisco do Oeste",
    "São Gonçalo do Amarante", "São João do Sabugi", "São José de Mipibu", "São José do Campestre",
    "São José do Seridó", "São Miguel", "São Miguel do Gostoso", "São Paulo do Potengi",
    "São Pedro", "São Rafael", "São Tomé", "São Vicente", "Senador Elói de Souza", 
    "Senador Georgino Avelino", "Serra de São Bento", "Serra do Mel", "Serra Negra do Norte",
    "Serrinha", "Serrinha dos Pintos", "Severiano Melo", "Sítio Novo", "Taboleiro Grande",
    "Taipu", "Tangará", "Tenente Ananias", "Tenente Laurentino Cruz", "Tibau",
    "Tibau do Sul", "Timbaúba dos Batistas", "Touros", "Triunfo Potiguar", "Umarizal",
    "Upanema", "Várzea", "Venha-Ver", "Vera Cruz", "Viçosa", "Vila Flor"
];